### ISSUE TITLE
essentials is not picking up the file some of tha value are not working

### ISSUE THREAD

**Issue by iLyPod** [X00LA/Bukkit-Essentials-worth.yml#1]
Problem selling items essentials is not detecting items listed

**Comment by iLyPod** [comment]
some of the values are not working  cant sell diamond chestpplate  or planks
says item cant be sold to server
when using /setworth   the item is added at the bottom but in a different format.
here is my file I added planks becuase it would not sell and diamond_chestplate. most of the items are not sellable.

my version of essentials: 
/essentials version
[INFO] Essentials Reloaded Pre2.13.1.6

my server version:
[INFO] This server is running CraftBukkit version git-Spigot-1470 (MC: 1.7.9) (Implementing API version 1.7.9-R0.1-SNAPSHOT)

The worth.yml after using /setworth

```
         Created by X00LA
```

   Made for MC 1.7.X and ready for MC 1.8
   Optimized for ideal balanced Economy!
   Report any issues on my Github-Page:
   https://github.com/X00LA/Bukkit-Essentials-worth.yml.git
   Feel free to create a ticket...

worth:
  stone: 3.64
  stone:1: 39.19
  stone:2: 54.08
  stone:3: 33.7
  stone:4: 46.51
  stone:5: 24.16
  stone:6: 33.35
  grass: 1.32
  dirt: 0.4
  dirt:1: 1.32
  dirt:2: 3.3
  cobblestone: 1.32
  planks: 4.55
  planks:1: 4.55
  planks:2: 4.55
  planks:3: 4.55
  planks:4: 4.55
  planks:5: 4.55
  sapling: 6.6
  sapling:1: 6.6
  sapling:2: 6.6
  sapling:3: 6.6
  sapling:4: 6.6
  sapling:5: 6.6
  sand: 0.66
  sand:1: 1.98
  gravel: 0.66
  gold_ore: 66.0
  iron_ore: 19.8
  coal_ore: 13.2
  log: 13.2
  log:1: 13.2
  log:2: 13.2
  log:3: 13.2
  log:4: 13.2
  log:5: 13.2
  log2: 13.2
  log2:1: 13.2
  leaves: 2.64
  leaves:1: 2.64
  leaves:2: 2.64
  leaves:3: 2.64
  leaves:4: 2.64
  leaves:5: 2.64
  glass: 2.73
  lapis_ore: 26.4
  lapis_block: 49.18
  dispenser: 47.48
  sandstone: 3.64
  sandstone:1: 6.94
  sandstone:2: 5.03
  noteblock: 55.74
  golden_rail: 129.84
  detector_rail: 43.44
  sticky_piston: 117.34
  web: 2.97
  tallgrass: 0.01
  tallgrass:1: 0.01
  tallgrass:2: 0.01
  deadbush: 0.01
  piston: 71.83
  wool: 6.6
  wool:1: 10.84
  wool:2: 14.9
  wool:3: 15.77
  wool:4: 10.36
  wool:5: 22.41
  wool:6: 12.87
  wool:7: 15.77
  wool:8: 15.33
  wool:9: 23.29
  wool:10: 13.75
  wool:11: 14.57
  wool:12: 18.22
  wool:13: 24.19
  wool:14: 10.36
  wool:15: 14.57
  yellow_flower: 1.32
  red_flower: 1.32
  red_flower:1: 3.3
  red_flower:2: 6.6
  red_flower:3: 2.31
  red_flower:4: 2.31
  red_flower:5: 2.31
  red_flower:6: 2.31
  red_flower:7: 2.31
  red_flower:8: 1.98
  brown_mushroom: 1.98
  red_mushroom: 1.32
  gold_block: 1153.84
  iron_block: 361.99
  stone_slab: 2.51
  stone_slab:1: 2.51
  stone_slab:3: 0.91
  stone_slab:4: 27.75
  stone_slab:5: 3.47
  stone_slab:6: 41.63
  stone_slab:7: 87.98
  brick_block: 40.22
  tnt: 94.72
  bookshelf: 144.34
  mossy_cobblestone: 10.93
  obisdian: 66.0
  torch: 4.73
  oak_stairs: 9.43
  chest: 50.28
  diamond_ore: 666.6
  diamond_block: 8197.2
  crafting_table: 25.14
  furnace: 14.57
  ladder: 10.12
  rail: 15.35
  stone_stairs: 2.73
  lever: 6.16
  stone_pressure_plate: 10.06
  wooden_pressure_plate: 12.57
  redstone_ore: 19.8
  redstone_torch: 9.8
  stone_button: 10.06
  ice: 9.24
  snow: 7.29
  cactus: 6.6
  clay: 21.86
  jukebox: 961.08
  fence: 13.01
  pumpkin: 13.2
  netherrack: 6.6
  soul_sand: 13.2
  glowstone: 58.29
  lit_pumpkin: 24.74
  stained_glass: 4.29
  stained_glass:1: 3.99
  stained_glass:2: 4.49
  stained_glass:3: 4.6
  stained_glass:4: 3.93
  stained_glass:5: 5.43
  stained_glass:6: 4.24
  stained_glass:7: 4.6
  stained_glass:8: 4.55
  stained_glass:9: 5.54
  stained_glass:10: 4.35
  stained_glass:11: 4.45
  stained_glass:12: 4.91
  stained_glass:13: 5.66
  stained_glass:14: 3.93
  stained_glass:15: 4.45
  trapdoor: 18.85
  stonebrick: 5.03
  stonebrick:1: 16.05
  stonebrick:2: 3.96
  stonebrick:3: 13.2
  brown_mushroom_block: 2.64
  red_mushroom_block: 2.64
  iron_bars: 15.08
  glass_pane: 1.41
  melon_block: 24.59
  vine: 6.6
  fence_gate: 29.91
  brick_stairs: 83.26
  stone_brick_stairs: 10.41
  mycelium: 13.2
  waterlily: 3.96
  nether_brick: 60.33
  nether_brick_fence: 124.89
  nether_brick_stairs: 124.89
  enchanting_table: 2221.47
  end_stone: 13.2
  dragon_egg: 1320.0
  redstone_lamp: 102.3
  wooden_slab: 3.14
  wooden_slab:1: 3.14
  wooden_slab:2: 3.14
  wooden_slab:3: 3.14
  wooden_slab:4: 3.14
  wooden_slab:5: 3.14
  sandstone_stairs: 1.37
  emerald_ore: 72.6
  ender_chest: 1326.28
  tripwire_hook: 25.42
  emerald_block: 498.02
  spruce_stairs: 9.43
  birch_stairs: 9.43
  jungle_stairs: 9.43
  beacon: 747.49
  cobblestone_wall: 1.82
  cobblestone_wall:1: 15.08
  wooden_button: 6.28
  anvil: 1659.52
  anvil:1: 872.75
  anvil:2: 436.37
  trapped_chest: 104.46
  light_weighted_pressure_plate: 256.41
  heavy_weighted_pressure_plate: 80.44
  daylight_detector: 119.96
  redstone_block: 49.18
  quartz_ore: 26.4
  hopper: 270.49
  quartz_block: 127.51
  quartz_block:1: 242.83
  quartz_block:2: 175.97
  quartz_stairs: 263.95
  activator_rail: 43.92
  dropper: 12.75
  stained_hardened_clay: 44.67
  stained_hardened_clay:1: 44.36
  stained_hardened_clay:2: 44.87
  stained_hardened_clay:3: 44.98
  stained_hardened_clay:4: 44.3
  stained_hardened_clay:5: 45.8
  stained_hardened_clay:6: 44.61
  stained_hardened_clay:7: 44.98
  stained_hardened_clay:8: 44.92
  stained_hardened_clay:9: 45.91
  stained_hardened_clay:10: 44.72
  stained_hardened_clay:11: 44.83
  stained_hardened_clay:12: 45.28
  stained_hardened_clay:13: 46.03
  stained_hardened_clay:14: 44.3
  stained_hardened_clay:15: 44.83
  stained_glass_pane: 2.22
  stained_glass_pane:1: 2.06
  stained_glass_pane:2: 2.33
  stained_glass_pane:3: 2.38
  stained_glass_pane:4: 2.03
  stained_glass_pane:5: 2.81
  stained_glass_pane:6: 2.19
  stained_glass_pane:7: 2.38
  stained_glass_pane:8: 2.35
  stained_glass_pane:9: 2.87
  stained_glass_pane:10: 2.25
  stained_glass_pane:11: 2.3
  stained_glass_pane:12: 2.54
  stained_glass_pane:13: 2.93
  stained_glass_pane:14: 2.03
  stained_glass_pane:15: 2.3
  acacia_stairs: 27.32
  dark_oak_stairs: 27.32
  slime: 163.94
  hay_block: 49.18
  carpet: 18.22
  carpet:1: 29.93
  carpet:2: 41.13
  carpet:3: 43.53
  carpet:4: 28.61
  carpet:5: 61.84
  carpet:6: 35.51
  carpet:7: 43.52
  carpet:8: 42.31
  carpet:9: 64.27
  carpet:10: 37.94
  carpet:11: 40.22
  carpet:12: 50.28
  carpet:13: 66.77
  carpet:14: 28.61
  carpet:15: 40.22
  hardened_clay: 31.99
  coal_block: 131.16
  packed_ice: 19.8
  double_plant: 3.96
  double_plant:1: 3.3
  double_plant:2: 0.01
  double_plant:3: 0.01
  double_plant:4: 1.32
  double_plant:5: 1.32
  iron_shovel: 48.89
  iron_pickaxe: 129.34
  iron_axe: 129.34
  flint_and_steel: 42.04
  apple: 3.96
  bow: 21.21
  arrow: 1.77
  coal: 10.56
  coal:1: 20.04
  diamond: 660.0
  iron_ingot: 29.15
  gold_ingot: 92.9
  iron_sword: 84.78
  wooden_sword: 16.91
  wooden_shovel: 14.96
  wooden_pickaxe: 27.53
  wooden_axe: 27.53
  stone_sword: 7.98
  stone_shovel: 14.96
  stone_pickaxe: 14.14
  stone_axe: 14.14
  diamond_sword: 1825.94
  diamond_shovel: 919.47
  diamond_pickaxe: 2741.07
  diamond_axe: 2741.07
  stick: 3.14
  bowl: 4.71
  mushroom_stew: 11.06
  golden_sword: 260.47
  golden_shovel: 136.88
  golden_pickaxe: 393.29
  golden_axe: 393.29
  string: 1.98
  feather: 0.66
  gunpowder: 13.2
  wooden_hoe: 21.24
  stone_hoe: 12.32
  iron_hoe: 89.11
  diamond_hoe: 1830.27
  golden_hoe: 265.08
  wheat_seeds: 1.32
  wheat: 3.96
  bread: 16.39
  leather_helmet: 76.08
  leather_chestplate: 121.72
  leather_leggins: 106.51
  leather_boots: 60.86
  chainmail_helmet: 142.83
  chainmail_chestplate: 228.53
  chainmail_leggins: 199.96
  chainmail_boots: 114.26
  iron_helmet: 201.1
  iron_chestplate: 321.77
  iron_leggins: 281.55
  iron_boots: 160.88
  diamond_helmet: 4554.0
  diamond_chestplate: 7286.4
  diamond_leggins: 6375.6
  diamond_boots: 3643.2
  golden_helmet: 641.02
  golden_chestplate: 1025.63
  golden_leggins: 897.43
  golden_boots: 512.82
  flint: 1.32
  porkchop: 9.9
  cooked_porkchop: 15.48
  painting: 43.8
  golden_apple: 162.73
  golden_apple:1: 12743.83
  sign: 14.01
  wooden_door: 37.71
  bucket: 120.66
  water_bucket: 72.6
  lava_bucket: 168.96
  minecart: 201.1
  saddle: 132.0
  iron_door: 241.33
  redstone: 3.96
  snowball: 1.32
  boat: 31.42
  leather: 13.2
  milk_bucket: 72.6
  brick: 7.29
  clay_ball: 3.96
  reeds: 1.32
  paper: 1.82
  book: 25.76
  slimeball: 13.2
  chest_minecart: 346.91
  furnace_minecart: 297.63
  egg: 0.66
  compass: 327.23
  fishing_rod: 18.47
  clock: 518.28
  glowstone_dust: 10.56
  fish: 3.96
  fish:1: 4.29
  fish:2: 1.98
  fish:3: 6.6
  cooked_fished: 7.29
  cooked_fished:1: 7.74
  cooked_fished:2: 4.55
  cooked_fished:3: 10.93
  dye: 3.96
  dye:1: 0.91
  dye:2: 10.93
  dye:3: 6.6
  dye:4: 3.96
  dye:5: 3.36
  dye:6: 10.27
  dye:7: 4.51
  dye:8: 4.83
  dye:9: 2.72
  dye:10: 9.64
  dye:11: 0.91
  dye:12: 4.83
  dye:13: 4.2
  dye:14: 1.26
  dye:15: 3.04
  bone: 6.6
  sugar: 1.82
  cake: 322.9
  bed: 46.18
  repeater: 47.6
  cookie: 20.04
  filled_map: 6.6
  shears: 80.44
  melon: 1.98
  pumpkin_seeds: 19.8
  melon_seeds: 19.8
  beef: 9.9
  cooked_beef: 15.48
  chicken: 6.6
  cooked_chicken: 10.93
  rotten_flesh: 1.32
  ender_pearl: 66.0
  blaze_rod: 132.0
  ghast_tear: 99.0
  gold_nugget: 14.24
  nether_wart: 33.0
  potion: 15.61
  potion:16: 67.08
  potion:32: 36.12
  potion:64: 27.01
  potion:8193: 229.19
  potion:8194: 95.09
  potion:8195: 158.77
  potion:8196: 98.04
  potion:8197: 123.47
  potion:8198: 312.11
  potion:8200: 36.32
  potion:8201: 218.26
  potion:8202: 233.89
  potion:8204: 150.08
  potion:8205: 101.68
  potion:8206: 445.5
  potion:8225: 330.86
  potion:8226: 145.79
  potion:8228: 149.87
  potion:8229: 184.97
  potion:8233: 315.78
  potion:8236: 221.68
  potion:8257: 321.75
  potion:8258: 136.69
  potion:8259: 224.57
  potion:8260: 140.67
  potion:8262: 436.18
  potion:8264: 52.05
  potion:8265: 306.67
  potion:8266: 324.69
  potion:8269: 145.79
  potion:8270: 620.25
  potion:16385: 334.5
  potion:16386: 149.44
  potion:16387: 237.32
  potion:16388: 153.51
  potion:16389: 188.61
  potion:16390: 448.93
  potion:16392: 68.34
  potion:16393: 319.42
  potion:16394: 340.98
  potion:16396: 225.32
  potion:16397: 158.54
  potion:16398: 633.0
  potion:16417: 474.8
  potion:16418: 219.41
  potion:16420: 225.03
  potion:16421: 273.47
  potion:16425: 453.99
  potion:16428: 324.13
  potion:16449: 462.24
  potion:16450: 206.84
  potion:16451: 328.12
  potion:16452: 212.46
  potion:16454: 620.14
  potion:16456: 90.05
  potion:16457: 441.42
  potion:16458: 466.28
  potion:16461: 158.54
  potion:16462: 874.16
  glass_bottle: 11.31
  spider_eye: 3.96
  fermented_spider_eye: 10.71
  blaze_powder: 91.08
  magma_cream: 47.97
  brewing_stand: 187.62
  cauldron: 281.55
  ender_eye: 216.77
  speckled_melon: 22.39
  fire_charge: 158.48
  writable_book: 41.92
  emerald: 66.0
  item_frame: 52.91
  flower_pot: 30.17
  carrot: 1.32
  potato: 0.66
  baked_potato: 2.73
  poisonous_potato: 0.33
  map: 471.69
  golden_carrot: 159.09
  skull:1: 66.0
  carrot_on_a_stick: 27.32
  nether_star: 330.0
  pumpkin_pie: 21.64
  fireworks: 246.99
  firework_charge: 101.75
  comparator: 952.4
  netherbrick: 10.93
  quartz: 23.1
  tnt_minecart: 408.24
  hopper_minecart: 650.79
  iron_horse_armor: 158.4
  golden_horse_armor: 462.0
  diamond_horse_armor: 3960.0
  lead: 14.57
  name_tag: 66.0
  record_13: 132.0
  record_cat: 132.0
  record_blocks: 132.0
  record_chirp: 132.0
  record_far: 132.0
  record_mall: 132.0
  record_mellohi: 132.0
  record_stal: 132.0
  record_strad: 132.0
  record_ward: 132.0
  record_11: 132.0
  record_wait: 132.0
  wood:
    '0': 4.55
  diamondchestplate:
    '0': 7286.4

**Comment by X00LA** [comment]
Hi!

That's a problem with the Version of Essentials. They use a new and different format for the worth.yml. I wrote to them and ask for cooperation but they are not interested. Please use my worth.yml to set the prices and use setworth to assign it to the file. I'm sorry for this but I havent time to recreate the whole file.
Eventually I make it new in summer holiday.

Regards,

X00LA
