### ISSUE TITLE
Updated file

### ISSUE THREAD

**Issue by Squawkers13** [X00LA/Bukkit-Essentials-worth.yml#2]
https://gist.github.com/Squawkers13/a0b12749bc16d5d32168

Created an updated version :)

It won't work with 1.8 though. (And I suspect yours won't either...)

**Comment by X00LA** [comment]
Good work!
I was too busy in the last time to make an update.
It's a ass full of work to do that and you have my full respect for making it.

Thank's!

P.S.: Updated my project readme. Now all credits goes to you. You no longer need to show my credits in the file.
