### ISSUE TITLE
Update to 1.13

### ISSUE THREAD

**Issue by killertunes** [X00LA/Bukkit-Essentials-worth.yml#4]
Please update for 1.13. Thanks.

**Comment by X00LA** [comment]
At the moment I cant because EssentialsX does'nt have the ID's implemented.
When EssentialsX have finished the update to 1.13.x I update the file as soon as possible.

**Comment by lifehome** [comment]
Hi, I think EssentialsX have updated the item names formatting for 1.13. Any chance to revisit this modification?

**Comment by X00LA** [comment]
Hello, at the moment I have a lot of work in real life so I does'nt know when I got time for updating the file.
I'm really sorry for that but real life goes first.
I hope I can update it soon. Keep an eye on the repository to see when I update it.

**Comment by axemwa** [comment]
So I assume we won't be able to sell and buy items anymore until this is fixed for 1.13?

**Comment by killertunes** [comment]
I "fixed" it myself after X00LA's response to my OP. Sure it's a lot of work but hey if it was easy everybody would be doing it. =) Thanks for giving me a base to work off of. Better than starting from scratch.

**Comment by Roukaysa** [comment]
> I "fixed" it myself after X00LA's response to my OP. Sure it's a lot of work but hey if it was easy everybody would be doing it. =) Thanks for giving me a base to work off of. Better than starting from scratch.

Well, can you share it with us?

**Comment by axemwa** [comment]
> 
> 
> > I "fixed" it myself after X00LA's response to my OP. Sure it's a lot of work but hey if it was easy everybody would be doing it. =) Thanks for giving me a base to work off of. Better than starting from scratch.
> 
> Well, can you share it with us?

https://ci.ender.zone/job/EssentialsX/765/

**Comment by queengooborg** [comment]
> Well, can you share it with us?

I've been running into the same problem while setting up a friend's server.  It's a wonderful price sheet, but alas, it would be nice to have it updated to 1.13.x, and even 1.14.x (with additional updates coming).  That's where I figured I might as well bite the bullet and take care of the conversion work myself, along with adding additional items introduced in both versions.

For anyone that wishes for a 1.13.x+ file, here it is!  https://gist.github.com/vinyldarkscratch/92d08120f0d6d25175f6c7a30e3ccac7
