### ISSUE TITLE
Price difference

### ISSUE THREAD

**Issue by niss1m** [X00LA/Bukkit-Essentials-worth.yml#6]
stone sells for 2.31$
stone button sells for 4.85$

..........

**Comment by X00LA** [comment]
That's not a error or a typo.
All prices have been calculated with profit margins for the collector, manufacturer and a certain tax. This ensures that you can make profits with it and not just calculate the price 1: 1.
If you just did the math 1:1, nobody would really make a profit and the work and time put in would not be rewarded.
The prices are calculated as in the RL.

**Comment by X00LA** [comment]
If you want to use these prices to sell goods, you should add a little more. I use on my servers:
10% for food and its raw materials.
20% for all materials like wooden planks etc.
25% for raw materials like ores, logs, etc., for chests and other manufacturing stations.
30% for tools of all kinds.
40% for weapons and armor.
50% for all Redstone parts.
Nobody has ever complained to me about my price rating.

**Comment by X00LA** [comment]
If you want to recalculate the prices for your liking you can do tis with [**Minecraft Economy Manager**](https://www.facebook.com/MinecraftEconomyManager/).

**Comment by niss1m** [comment]
I understand..


Thanks for the quick reply tho
